-- This script populates the database with initial data for development and testing.

--
-- Seed the `values` table with the four core company values.
--
INSERT INTO `values` (name, description) VALUES
('Be Cool', 'For demonstrating grace under pressure and maintaining a positive attitude.'),
('Be Courageous', 'For taking on tough challenges and speaking up for what is right.'),
('Be Connected', 'For collaborating effectively and building strong relationships.'),
('Be Curious', 'For asking great questions and exploring new ways of doing things.');

--
-- Seed the `users` table with an admin and a few standard users.
--
-- IMPORTANT: The 'password_hash' values here are placeholders. In a real application,
-- these would be generated by the backend using a secure hashing algorithm like bcrypt.
-- For initial testing, a sample password like 'password123' could correspond to these hashes.
--
INSERT INTO users (full_name, email, password_hash, is_admin, award_balance, spending_balance) VALUES
('Admin User', 'admin@kudos.dev', '$2b$10$D9g.PAyGz.5bDE4sT2aHLehMvYfTDbwVI0wopXn9j3sBvBwO3iA/S', TRUE, 100, 0),
('Standard User One', 'user1@kudos.dev', '$2b$10$D9g.PAyGz.5bDE4sT2aHLehMvYfTDbwVI0wopXn9j3sBvBwO3iA/S', FALSE, 100, 0),
('Standard User Two', 'user2@kudos.dev', '$2b$10$D9g.PAyGz.5bDE4sT2aHLehMvYfTDbwVI0wopXn9j3sBvBwO3iA/S', FALSE, 100, 50);